# Generated by Django 6.0 on 2025-12-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Optional banner image for the homepage category section.', null=True, upload_to='category_banners/'),
        ),
    ]
